### PR TITLE
Fix "Powershell not spawned" error.

### LINKED ISSUE #35: "Powershell not spawned"
I get an error now (on master) saying "'powershell' could not be spawned.  Is it installed on your path", with a sidebar opening with error

Window load time: 1219ms
events.js:141 Uncaught Error: spawn powershell ENOENT

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Fixes #35.

### CODE REVIEW

**Comment by Varanas** [comment]
Thanks for cleaning this up!

**Comment by MichaelHatherly** [comment]
No prob, presumably this works on osx? I've not tested that.

**Comment by Varanas** [comment]
The original [PR](https://github.com/JunoLab/atom-julia-client/pull/21) was tested on OS X, so this should work as well

**Comment by MichaelHatherly** [comment]
OK, thanks.

**Pull request merged**
