### PR TITLE
move to the last [row, col] in the next block

### PR DESCRIPTION
**Pull request by pfitzseb**
instead of preserving the column and staying on the first row. I realize the column-preserving probably happened for a reason, but it feels strange to me ;)

### CODE REVIEW

**Comment by MikeInnes** [comment]
Yeah I quite like the current behaviour, although I'm not adamant about it. Quick poll – anyone else have any preferences?

If you're just shooting down the file it makes no odds anyway – are there any situations where it would?

**Comment by Varanas** [comment]
Well, I find it easier/faster to find out which code block will be executed -- when I'm reading the file top down, and follow the cursor movements, I always know up to where my code has been executed. Sure, indentation or even reading the block delimiters works, but isn't as fast.

Also, this change is something I made first thing after I first used the eval-and-move feature, so it seems like my expectations as to what it does weren't met. Dunno how this is for anyone else though.

**Comment by pfitzseb** [comment]
Hm, polls don't work very well when there's only two people in them. :D
So yeah, bumping.

**Comment by spencerlyon2** [comment]
If I had to choose I'd say move to the end

**Comment by pfitzseb** [comment]
So, how about this? :)

**Comment by MikeInnes** [comment]
Looks like I've been outvoted (though whether or not it's statistically significant... ;) Go ahead!

**Comment by pfitzseb** [comment]
Well, twice as many people were in favour of this change... :D

**Pull request merged**
