### PR TITLE
debug file

### PR DESCRIPTION
**Pull request by pfitzseb**
Requires https://github.com/JunoLab/Atom.jl/pull/269.
Requires https://github.com/JunoLab/atom-ink/pull/255.
Requires https://github.com/JunoLab/atom-ink/pull/256.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Peek 2020-02-10 16-57

**Comment by aviatesk** [comment]
Do you want
- tool-bar icon for invoking file debugging ?
- menus ?

**Comment by pfitzseb** [comment]
Ah, right, forgot about that. We can now also add commands to debug the currently selected block etc.

**Comment by aviatesk** [comment]
> We can now also add commands to debug the currently selected block

Maybe `Julia Debug: Run Block` and `Julia Debug: Step Through Block` ?

**Comment by pfitzseb** [comment]
Yeah, that sounds goood.

**Comment by aviatesk** [comment]
> > We can now also add commands to debug the currently selected block
> 
> Maybe `Julia Debug: Run Block` and `Julia Debug: Step Through Block` ?

Done ;) Also added `Run Cell` and `Step Through Cell`.

**Comment by aviatesk** [comment]
@pfitzseb don't you mind renaming `run-and-move` to `run-block-and-move` ?

**Comment by aviatesk** [comment]
As for menus, how about those submenus `Run` and `Debug` ?:
image

**Comment by pfitzseb** [comment]
image

**Comment by pfitzseb** [comment]
> @pfitzseb don't you mind renaming run-and-move to run-block-and-move ?

Mh, I'd like to keep commands that are likely used by others the same, but maybe it's fine to rename this one.

> As for menus, how about those submenus Run and Debug ?:

I don't like deeply nested menus much. Imho the current structure is still fine (and we don't have too many items yet).

**Comment by aviatesk** [comment]
> Mh, I'd like to keep commands that are likely used by others the same, but maybe it's fine to rename this one.

Yeah, this may break some user's own keybinding. Suggested because you did some renaming around debugging commands, but yes `run-and-move` is so much often used that them I guess.

> I don't like deeply nested menus much. Imho the current structure is still fine (and we don't have too many items yet).

Okay, let's just keep menus then.

**Pull request merged**
