### PR TITLE
Pending open

### PR DESCRIPTION
**Pull request by aviatesk**
Introduces `Open files in pending state` config.

Please refer to the description of the config for why I want to introduce this: 
https://github.com/JunoLab/atom-julia-client/pull/579/files#diff-5655a196ecf76f9731b64509e8b7676aR141-147

The corresponding PR on atom-ink is: https://github.com/JunoLab/atom-ink/pull/208

### CODE REVIEW

**Comment by aviatesk** [comment]
> I think we should just reuse atom.config.get('core.allowPendingPaneItems') instead of introducing our own config option.

Sounds good. Is it okay that it would change the file-opening behaviour implicitly from the an user's veiw point ?

> IMHO we have too many options as is.

Totally agree. This is just a talk of appearance, but how about collapsing all the top level config like this ?
image

This would make config appear more structured and may navigate an user better.

**Comment by pfitzseb** [comment]
> Sounds good. But is it okay that it would change the file-opening behaviour implicitly from the an user's veiw point ?

Should be ok, imho, especially since the core setting doesn't precisesly specify when it is used.

> This is just a talk of appearance, but how about collapsing all the top level config like this ?

Sure, sounds good.

**Comment by aviatesk** [comment]
Addressed in the commits above 👍

**Comment by aviatesk** [comment]
@pfitzseb Please merge this first before #573

**Pull request merged**
