### PR TITLE
Add keybindings for linux/windows.

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Mac-equivalent keybindings for Linux/Windows.

Have you decided on a keybinding for ``clear-inline-results``?

### CODE REVIEW

**Comment by one-more-minute** [comment]
I'm happy with these in theory, but have you checked they don't conflict with anything important? `Ctrl-.` will show you what keybindings are being activated.

**Comment by MichaelHatherly** [comment]
``window:toggle-dev-tools`` is bound to ``ctrl-shift-i`` so we should probably pick something else.

**Comment by one-more-minute** [comment]
`Ctrl-Alt-I` seems to be free on linux, so maybe we can just replace `Ctrl-Shift` with `Ctrl-Alt` on non-OS X.

**Comment by MichaelHatherly** [comment]
Yeah, no conflicts there it seems.

**Comment by one-more-minute** [comment]
Cool, thanks

**Pull request merged**
