### PR TITLE
project monitor tile

### PR DESCRIPTION
**Pull request by aviatesk**
image

requires https://github.com/JunoLab/Atom.jl/pull/330

- [x] basic implementaion
- [x] command export

### CODE REVIEW

**Comment by aviatesk** [comment]
I feel like I want to unify the terminologies of "environment" and "project", currently we use:
- "environment" in frontend (commands, etc)
- "project" in backend (Julia side)

**Comment by pfitzseb** [comment]
Maybe we should have `Env: JunoLab` in the tile and `Module: Atom` in the module tile to make it easier to figure out what one is looking at?

**Comment by aviatesk** [comment]
sounds nice idea, it's really confusing when I had two subsequent `Atom` tiles.

**Comment by aviatesk** [comment]
now they look:
image

I have to admit they now occupy even more spaces though, but who complains.

**Comment by pfitzseb** [comment]
`E: JunoLab`/`M: Atom` maybe? Should be clear enough with a tooltip.

**Comment by aviatesk** [comment]
> `E: JunoLab`/`M: Atom` maybe? Should be clear enough with a tooltip.

hm, imho I prefer the first idea (`Env: ` and `Module: `) ...

**Pull request merged**
