### PR TITLE
Modified ps script for working interrupts on Windows

### PR DESCRIPTION
**Pull request by Varanas**
and a couple of windows fixes in process.coffee.

@one-more-minute: The additional `cwd: @workingDir()` you added to the `powershell` invocation errors for me -- powershell cannot be spawned with it there.

I also added the early return in `checkExe` you suggested.

### CODE REVIEW

**Comment by one-more-minute** [comment]
Nice one. Is there any way for us to respect the working directory? Perhaps it could be passed through to powershell as an extra option?

**Comment by Varanas** [comment]
Yeah, probably. I'll look into it (probably won't get to it until tomorrow though). 

Also, can you check that this works for you? Can't try it on another PC right now.

**Comment by one-more-minute** [comment]
Yup, will let you know ASAP.

**Comment by one-more-minute** [comment]
Works great!

**Comment by Varanas** [comment]
Working dir should be set now.

There may or may not be a problem with `@workingDir()` though -- it seems like the current project folder can be a file. We should probably check for that.

**Comment by one-more-minute** [comment]
One last issue: If the Julia session shuts down (e.g. `exit()`, the wrapper lives on, so Atom thinks Julia is still running. For now I've removed the indirection from the kill command to work around this. I'll see if there's a way to listen to process exits from ps.

**Comment by Varanas** [comment]
The changes in the next to last commit wouldn't help with that, would they?
If Julia dies the wrapper still has no way of knowing that, but the change would keep Julia alive even though the wrapper is killed.

**Comment by Varanas** [comment]
I thought something like 
```powershell
Register-ObjectEvent -InputObject $proc -EventName exited -Action {
	echo "Julia died, terminating the wrapper."
	Stop-Process $pid # Exit doesn't work either
}
```
might work, but it doesn't...

**Comment by one-more-minute** [comment]
It occurs to me that we could also listen for client disconnects and kill the wrapper then.

**Comment by Varanas** [comment]
Yup, those should indeed be handled in some way since they're just spamming the console anyways...

**Comment by one-more-minute** [comment]
Let me know what you think of the latest commit and we can merge this.

**Comment by Varanas** [comment]
LGTM, but haven't had the chance to try it yet.

**Comment by Varanas** [comment]
It's been a long and arduous way, but we finally got there.

**Comment by Varanas** [comment]
@one-more-minute Would you tag a patch release please? Actually living up to what we promise in the changelog seems to justify one ;)

**Comment by one-more-minute** [comment]
I think the credit is all yours here, but yes, definitely glad to get there in the end. Will go ahead and tag a patch.

**Comment by Varanas** [comment]
Thanks! I'll try to figure out what `apm` doesn't like about my setup or whatever so I don't have to bug you everytime when a patch should be tagged;)

**Pull request merged**
