### PR TITLE
follow new ink api

### PR DESCRIPTION
**Pull request by pfitzseb**
https://github.com/JunoLab/atom-ink/pull/127

### CODE REVIEW

**Comment by pfitzseb** [comment]
The  `Send to console` button kinda breaks lazy results, will have to look into that. For now it might be better to get the stable changes in and leave that button for another PR.

**Comment by MikeInnes** [comment]
Yup, seems sensible.

**Comment by pfitzseb** [comment]
That code now lives in https://github.com/JunoLab/atom-julia-client/tree/sp/sendtoconsole.

**Comment by pfitzseb** [comment]
This isn't really breaking (we didn't use the `.julia` class we set), so I'm going ahead and merge this.

**Pull request merged**
