### PR TITLE
Eslint + GithubActions instead of Travis/Appveyor

### PR DESCRIPTION
**Pull request by aminya**
- [X] Use Github actions instead of Travis and Appveyor. See the running actions here: 
https://github.com/aminya/atom-julia-client/actions/runs/68177380
- [X] Add Eslint for js + coffee + json

P.S: no typescript config is in this PR. It's pure JS/Coffee.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Why are Github Actions better than travis?

**Comment by aminya** [comment]
- It does whatever those travis and appveyors did
plus:
- The configuration is easier.
- Easier [dependency installation](https://github.com/aminya/atom-julia-client/blob/d42225c010262cad076956f7138b6ea19d1985a6/.github/workflows/ci.yml#L36)
- We can use a [custom linter](https://github.com/aminya/atom-julia-client/blob/d42225c010262cad076956f7138b6ea19d1985a6/.github/workflows/ci.yml#L57)
- We can write [custom tests](https://github.com/aminya/atom-julia-client/blob/d42225c010262cad076956f7138b6ea19d1985a6/.github/workflows/ci.yml#L43), although not enabled now since spec fails anyways even locally.

https://github.com/aminya/atom-julia-client/blob/github_actions/.github/workflows/ci.yml

**Comment by aminya** [comment]
Don't merge this for a second. I need to bring Eslint to this PR too

**Comment by aminya** [comment]
This is ready to get merged now.

**Comment by aminya** [comment]
What's wrong with this? @aviatesk

**Comment by aviatesk** [comment]
sorry for closing without providing reasons, @aminya 
I closed since:
- test body itself doesn't seem to work (because it's commented out)
- I don't want to those ESlint stuff to get in

I'm thinking of moving julia-client's CI to use GH actions, but it would be nice if you want to keep work on this:
- remove linting setups
- setup CI in a way that you don't ignore the existing test

Let me know you want to reopen this.

**Comment by aminya** [comment]
The tests doesn't work locally. This isn't the problem of this PR.

**Comment by aminya** [comment]
Also, Eslint is configured as just warnings. It doesn't forces anything. It is possible to configure it to use Standard.

https://github.com/standard/eslint-config-standard

The standard way to do online linting is using Eslint framework. Configuration depends on the usecase.

**Pull request closed without merging**
