### PR TITLE
In-editor Profile Viewer

### PR DESCRIPTION
**Pull request by pfitzseb**
screenshot_20170530_182102

All the complicated stuff was done by @MikeInnes, I just rebased and made some few improvements.

Depends on https://github.com/JunoLab/atom-ink/pull/133 and https://github.com/JunoLab/Juno.jl/pull/60.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Awesome!

**Comment by MikeInnes** [comment]
Heads up, I rebased this to remove an unrelated change

**Comment by MikeInnes** [comment]
Originally we just used the generic plot pane for this, which I think makes a lot of sense. Is there a reason to have a profiling-specific pane?

**Comment by pfitzseb** [comment]
I found a profiler specific pane pretty nice since it doesn't destroy any plots then. In principle we could just update our plot pane to handle multiple plots, but that seems like to much trouble for the first iteration of this...

Not sure what doesn't work for you when clicking the profiler boxes -- is a wrong file opened or none at all?

That zooming took me forever to get right, but that was mostly because I tried to use random code from the internet instead of thinking for myself :D

**Comment by MikeInnes** [comment]
It just opens a blank `untitled-2fb38...` file for me.

I partly worry that people will get used to having the new pane and we'll have to stick with it even once we have a better solution. But breaking that might be the lesser evil; it doesn't bother me but I don't do much plotting.

**Comment by pfitzseb** [comment]
Ah, yeah, that's #350. Do you think that's blocking? I dunno how many people work regularly work with untitled buffers...

**Comment by MikeInnes** [comment]
Doesn't have to block this pr, would be nice to get it into the release though

**Comment by pfitzseb** [comment]
Alright, done :)

Re new pane vs PlotPane: I really think a new pane item is better for now, the other option is imho to annyoing if you have a plot open.

**Comment by pfitzseb** [comment]
@MikeInnes Do you think this is good to go?

**Comment by MikeInnes** [comment]
Yeah this looks good to me :+1:

**Comment by mkborregaard** [comment]
*runs `Pkg.checkout("atom-julia-client")` *

**Comment by MikeInnes** [comment]
Awesome, thanks for pushing this along

**Comment by mkborregaard** [comment]
It works! Also great that you can zoom and pan with the mouse, jump into files, etc. This is IMO one of the best inventions after someone came up with toasting day-old bread.
Could there be a possibility of opting out of the top boxes where Atom, CodeTools etc deal process and send the command to julia?

**Comment by pfitzseb** [comment]
Yeah, that should basically be the same scrubbing we already do for stacktraces.

**Pull request merged**
