### PR TITLE
Much nicer method view panel

### PR DESCRIPTION
**Pull request by pfitzseb**
This implements a nicer and searchable frontend for the `toggle methods` command, as mentioned in #76.

methodview

[Julia side](https://github.com/JunoLab/Atom.jl/pull/20).
~~[Ink side](https://github.com/JunoLab/atom-ink/pull/25).~~

ToDo:
- [x] Default shortcut!
- [ ] style improvements, maybe? I'm open to suggestions. cc @spencerlyon2, @mfcd
- [x]  highlighting of matched keywords. That is actually not all that hard, see [here](https://github.com/atom/command-palette/blob/86741d106dbdc4860922e1b8bfded97dd699c274/lib/command-palette-view.coffee#L74-L92), but I didn't feel like copying their method just like that...
- [x]  Just thought of it -- this should probably be implemented with a `promise`, right?
- [x]  Errors should be handled gracefully instead of not at all.

### CODE REVIEW

**Comment by one-more-minute** [comment]
So to clarify, this is designed to replace the Juno/LT approach of just displaying the methods inline, right? Or is it more to augment it?

**Comment by Varanas** [comment]
Yeah, pretty much. Could also be viewed as a replacement for `Ctrl-R` in plain Atom. 

This doesn't change the rendering of e. g.  `methods(sin) `.

**Comment by Varanas** [comment]
Highlighting is implemented:
highlighted

If no one has any problems with the styling or any other suggestions, this should be good to merge.

**Comment by Varanas** [comment]
We should really have a default shortcut for this!
Suggestion:
Use `C-Shift-J C-Shift-M` for selecting modules and `C-J C-M` for getting methods? Would be close to the `C-J C-D` we currently use for docs. Thoughts? cc @one-more-minute

**Comment by spencerlyon2** [comment]
Quick question, will the path separator be `/` on unix systems?

**Comment by Varanas** [comment]
Yup. Should be exactly the same as in backtraces and the like.

**Comment by spencerlyon2** [comment]
OK great! I like your keymap suggestion

**Comment by spencerlyon2** [comment]
What would it look like if each method had a shorter list item? It'd be nice to see more at a time

**Comment by Varanas** [comment]
What about this?
unbenannt-1

**Comment by spencerlyon2** [comment]
I like it

**Comment by one-more-minute** [comment]
This is looking really good – big :+1: for screenshots ;) Any chance of having the sig on the left and the path on the right? There's also a method somewhere which will humanise package paths, i.e. `C:\Users\...\Lazy\...` :arrow_right: `Lazy\src\Lazy.jl` -- may well be worth applying that.

I've been thinking a bit how these things should fit together, so that all of our UI components have a clear purpose. Here's my proposal:

* We have one `docs` command which folds docstrings and methods together in a tree view (similar to the rendering of functions currently). Docstring is shown and methods are hidden by default for click-and-browse exploration.
* We also have a `jump to definition` command which loads up the appropriate file/location for the given object. If there's only one go straight there, if not launch this method view to navigate quickly to the right one. The command itself would no longer be method-specific.

How does that sound? It's not critical that this is all working thoroughly for this PR to be worth merging, of course, but I think that's what we should aim towards. (Open to other ideas of course!)

**Comment by Varanas** [comment]
Yeah, that sounds like a good plan.

Couple of thoughts:
- This PR implements `methodswith(word)` when `word` is a type instead of a method -- would we drop that functionality or fold it into the docs command (not ideal, since that's not searchable)?
- How could `jump to definition` be implemented? Combination of the `symbols-view` approach (for local definitions) and `methods`?
- Do you have any ideas how refs ot other methods should work in the inline docs? Open a new pane or a browser window to display those or have it all inline? Matlab for example takes the first approach -- you get short `docs` with `help method` and clicking on the links to related methods opens a separate documentation browser. I think this may be better than doing all that inline, but I'm not sure.
- Imho getting to the definition isn't everything there is to a method view command -- it's also great for exploration of the available functions. We could conceivably have some way to open docs from there as well.
- The methodview logic should probably be used by autocomplete as well: It'd be super cool to get a list of methods (and maybe even a short doc string) after typing the opening paren, kinda like in VS:
vs
Of course we won't quite get to that level since Julia is a dynmic language, but I really like that direction.

Okay, went a bit on a tangent there, but a bit of brainstorming can't hurt ;)

**Comment by Varanas** [comment]
This is now mostly superseded by https://github.com/JunoLab/atom-ink/pull/34.

**Pull request closed without merging**
