### PR TITLE
RFC: First stab at module eval in console

### PR DESCRIPTION
**Pull request by spencerlyon2**
This is the atom side of having the console evaluate into the Julia module of the last open julia buffer.

see JunoLab/Atom.jl#8

### CODE REVIEW

**Comment by spencerlyon2** [comment]
ping! this has been working nicely for me

**Comment by Varanas** [comment]
Whoops, completly forgot about this one, sorry.
While this certainly works, I'm not sure I'd really want this behaviour. It seems more convenient to me to either have the console always evaluate to `Main` or be able to choose the module to eval into (possibly with a setting to link the current editor's module with it). 
That said, I haven't done any work with this commit yet, so the above is purely theoretical ;)

**Comment by one-more-minute** [comment]
Yeah, this is definitely a good step in the right direction but I'm not sure that this is the right interface either. It feels a bit too "spooky action at a distance" to me, e.g. if the module you're working in switches out from under you because you left the cursor in the wrong buffer (or in the wrong place within it).

How about something more similar to the way blank editors work – i.e. you start out in Main and can switch at will?

**Comment by ssfrr** [comment]
I think that syncing the module of the editor and console makes sense,
but maybe if the console prompt changed to reflect which module you're
evaluating into it would feel more obvious what's going on?

**Comment by spencerlyon2** [comment]
I'm with @ssfrr here. 

To me I use the secondary buffer as a more permanent scratchpad and then I move to the REPL if I want high-latency interaction. It has been really convenient to be able to seamlessly move from buffer to REPL and not have to change anything

**Comment by spencerlyon2** [comment]
Thinking out loud here...

What if there was an option or something configurable in the settings that people could toggle on or off depending on whether or not they want the working module for the REPL to mirror the module from the last active Julia buffer? 

If people say yes, then my workflow described above would work seamlessly

If they say no, then we could implement what @one-more-minute suggests about having more state in the package that tracks the working module for the REPL (starts at Main, can be changed to anything just like Julia buffers).

**Comment by Varanas** [comment]
I think having both would be great :)
So we can set the module manually and have some nice little icon next to it to automatically link the REPL's module to the current editor -- and since I can see use cases for both behaviours I wouldn't want to go into the settings menu each time I want to change it.

**Comment by Varanas** [comment]
I think you can modify [this](https://github.com/JunoLab/atom-julia-client/blob/04ac902ed03db7295a49d0fcf36ae5e82672d1ba/lib/modules.coffee#L31-L43) (or something in that file... ;)) so that the module chooser shows up in the status bar at the bottom when the cursor is in the console, that'd be the best solution. If we were to throw a setting and into the mix you could then get this behavior as well.

**Comment by spencerlyon2** [comment]
feature implemented

**Pull request closed without merging**
