### PR TITLE
rotate step-in/-out buttons

### PR DESCRIPTION
**Pull request by pfitzseb**
image

### CODE REVIEW

**Comment by ssfrr** [comment]
I'm really tweaking the shade of the bikeshed here, but would it be possible to tilt them so they're facing to the right? so "step-into" is down-right, and "step-out-of" is up-right?

**Comment by pfitzseb** [comment]
Shouldn't step out point to the upper left then?

**Comment by ssfrr** [comment]
My mental model is that time goes left-to-right. And time marches inexorably onwards. More specifically, when you step-out of a function you don't end up returning to where you came from, you've progressed later into the upper stack frame

**Comment by DNF2** [comment]
Hmm. I'm always thinking, 'down' is the next line of code, so the arrow of time is downwards.

But there's probably no good way to conform to everyones mental model. The way people visualize time, for example, varies a lot. Some see the year moving 'circularly counter clockwise', some clockwise, some along a square perimeter, some like a three-dimensional askew torus, etc. etc. And some are _really_ weird.

**Comment by ssfrr** [comment]
Sure that's fair. I'm happy with whatever outcome.

Also @jkrumbiegel mentioned he might take a crack at something as well.

**Comment by aviatesk** [comment]
I'm afraid but I would like to tell my understanding -- at first "down" to step out and "up" to step into looked very weird to me, but then I could convince myself that they make sense in terms of they are very consistent with how a callstack and workspace view appear.
So for now, at least to me, making them vertical while keeping them "down" to step out and "up" to step into might be best.
Well, I really agree with that not everyone will respect consistency with other features here ...

**Comment by jkrumbiegel** [comment]
I posted this in the slack channel as well, could be another idea:

The blue line shows the "until selected line" concept a bit better maybe, and for me the step in and out versions are a bit more intuitive.

grafik

**Comment by ssfrr** [comment]
Lovely - Do you think it would be good to shorten the arrow on the "until selected line" icon so it stops at the line? Might be visually more noisy so maybe not a good idea.

**Comment by jkrumbiegel** [comment]
I thought the same, but then again that might be taken to mean that the other arrow goes over multiple lines, although it's just supposed to evoke "down" and "lines"

**Comment by jkrumbiegel** [comment]
grafik

**Comment by jkrumbiegel** [comment]
how about this instead? 
grafik

**Comment by ssfrr** [comment]
gorgeous.

**Comment by pfitzseb** [comment]
Closing in favor of https://github.com/JunoLab/atom-julia-client/pull/693.

**Pull request closed without merging**
